version: '3'
services:
  redis:
    build: ./dockerfiles/redis/
    container_name: 'redis'
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./data:/data
    networks:
      - backend
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
networks:
  backend: