version: '3'
services:
  redis:
    build: ./dockerfiles/redis/
    container_name: 'redis'
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./data:/data
    networks:
      - backend
    environment:
      - REDIS_PASSWD=${REDIS_PASSWD}
      - REDIS_PORT=${REDIS_PORT}
    
  # request_limit_server:
  #   build: .
  #   container_name: 'request_limit_server'
  #   restart: always
  #   ports:
  #     - ${PORT}:${PORT}
  #   networks:
  #     - backend
  #   environment:
  #     - NODE_ENV=${NODE_ENV}
  #     - REDIS_EXPIRE_TIME=${REDIS_EXPIRE_TIME}
  #     - REDIS_LIMIT_IP_COUNT=${REDIS_LIMIT_IP_COUNT}
  #     - REDIS_HOST=${REDIS_HOST}
  #     - REDIS_PORT=${REDIS_PORT}
  #     - REDIS_PASSWD=${REDIS_PASSWD}
  #     - APP_NAME=${APP_NAME}
  #     - PORT=${PORT}
  #     - IS_RUN_ON_DOCKER=true
  #   depends_on:
  #     - redis

networks:
  backend: